# Generated by Django 3.1.7 on 2021-04-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Человекочитаемый идентификатор')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос на контакт',
                'verbose_name_plural': 'Запросы на контакт',
                'db_table': 'contact_requests',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'db_table': 'faqs',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('company', models.CharField(max_length=255, verbose_name='Фирма')),
                ('feedback_text', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Человекочитаемый идентификатор')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('long_description', models.TextField(verbose_name='Общее описание')),
                ('technical_details', models.TextField(verbose_name='Технические характеристики')),
                ('brochure', models.FileField(upload_to='product_brochures', verbose_name='Брошюра')),
                ('standard_of_equipment', models.FileField(upload_to='product_standards_of_equipment', verbose_name='Стандарт оснащения')),
                ('commercial_proposal_file', models.FileField(upload_to='commercial_proposals', verbose_name='Файл КП')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Принадлежит категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='product_images', verbose_name='Изображение продукта')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product', verbose_name='Принадлежит продукту')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('origin', models.CharField(choices=[('order_origin_telegram_bot', 'Telegram чат-бот'), ('order_origin_website', 'Веб-сайт')], max_length=255, verbose_name='Источник')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Обработан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chosen_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='core.product')),
            ],
            options={
                'verbose_name': 'Запрос КП',
                'verbose_name_plural': 'Запросы КП',
                'db_table': 'orders',
            },
        ),
    ]
