# Generated by Django 3.2.4 on 2021-06-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Человекочитаемый идентификатор')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос на контакт',
                'verbose_name_plural': 'Запросы на контакт',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('company', models.CharField(max_length=255, verbose_name='Фирма')),
                ('feedback_text', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Человекочитаемый идентификатор')),
            ],
            options={
                'verbose_name': 'Родительская категория',
                'verbose_name_plural': 'Родительские категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название (короткое)')),
                ('name_search', models.CharField(default='Нет', max_length=400, unique=True, verbose_name='Название для поиска (длинное)')),
                ('slug', models.SlugField(verbose_name='Человекочитаемый идентификатор')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('long_description', models.TextField(blank=True, verbose_name='Общее описание')),
                ('technical_details', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='product_brochures', verbose_name='Брошюра')),
                ('standard_of_equipment', models.FileField(blank=True, null=True, upload_to='product_standards_of_equipment', verbose_name='Стандарт оснащения')),
                ('commercial_proposal_file', models.FileField(blank=True, null=True, upload_to='commercial_proposals', verbose_name='Файл КП')),
                ('is_used', models.BooleanField(default=True, verbose_name='БУ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Принадлежит категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='Telegram ID')),
                ('step', models.CharField(default=1, max_length=5, verbose_name='Шаг')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='product_images', verbose_name='Изображение продукта')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product', verbose_name='Принадлежит продукту')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productmanufacturer', verbose_name='Производитель'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_region', models.CharField(blank=True, max_length=255, verbose_name='Регион эксплуатации')),
                ('client_type', models.CharField(choices=[('legal_entity', 'Юридическое лицо'), ('individual', 'Физическое лицо')], default='legal_entity', max_length=255, verbose_name='От лица')),
                ('organization_full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное наименование организации')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('origin', models.CharField(choices=[('order_origin_telegram_bot', 'Telegram чат-бот'), ('order_origin_website', 'Веб-сайт')], max_length=255, verbose_name='Источник')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Обработан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chosen_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='core.product')),
            ],
            options={
                'verbose_name': 'Запрос КП',
                'verbose_name_plural': 'Запросы КП',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='core.parentcategory'),
        ),
    ]
