# Generated by Django 3.1.7 on 2021-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210424_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='technical_details',
            field=models.TextField(blank=True, verbose_name='Технические характеристики'),
        ),
    ]
