# Generated by Django 3.1.7 on 2021-05-02 20:53

from django.db import migrations, models
import django.db.models.deletion

from core.models import ParentCategory


def create_parent_category(apps, schema_editor):
    ParentCategory.objects.create(id=1, name='Temp', slug='temp')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20210424_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Человекочитаемый идентификатор')),
            ],
            options={
                'verbose_name': 'Родительская категория',
                'verbose_name_plural': 'Родительские категории',
                'db_table': 'parent_categories',
            },
        ),
        migrations.RunPython(create_parent_category),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories',
                                    to='core.parentcategory'),
            preserve_default=False,
        ),
    ]
