# Generated by Django 3.1.7 on 2021-05-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210505_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_type',
            field=models.CharField(choices=[('legal_entity', 'Юридическое лицо'), ('individual', 'Физическое лицо')], default='legal_entity', max_length=255, verbose_name='От лица'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='order',
            name='operation_region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион эксплуатации'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное наименование организации'),
        ),
    ]
