# Generated by Django 3.1.7 on 2021-05-28 11:42

from django.db import migrations, models
import django.db.models.deletion


def create_temp_brand(*args, **kwargs):
    from core.models import ProductManufacturer
    ProductManufacturer.objects.create(id=1, name='Brandname')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210511_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturers',
            },
        ),
        migrations.RunPython(create_temp_brand),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productmanufacturer', verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
