# Generated by Django 3.1.7 on 2021-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210528_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_search',
            field=models.CharField(default='Нет', max_length=400, unique=True, verbose_name='Название для поиска'),
        ),
    ]
