# Generated by Django 3.2.4 on 2021-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210623_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='ID пользоваетеля Tg')),
                ('step', models.CharField(max_length=5, verbose_name='Шаг')),
                ('phone', models.CharField(max_length=14, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contactrequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='faq',
            table=None,
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parentcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productmanufacturer',
            table=None,
        ),
    ]
