# Generated by Django 3.2.4 on 2021-06-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210626_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategory',
            name='upcat',
        ),
        migrations.AddField(
            model_name='product',
            name='is_used',
            field=models.BooleanField(default=True, verbose_name='БУ'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='step',
            field=models.CharField(default=1, max_length=5, verbose_name='Шаг'),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='userid',
            field=models.CharField(max_length=50, verbose_name='Telegram ID'),
        ),
        migrations.DeleteModel(
            name='IsUsed',
        ),
    ]
